### ISSUE TITLE
upgrade to react-native 0.59

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/observe#1]
https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059#updated-jsc-means-performance-gains-and-64-bit-support-on-android

**Comment by sethvincent** [comment]
Useful repo showing what changes need to be made in a basic app when upgrading react-native: https://github.com/react-native-community/rn-diff-purge

The diff for our current version, 0.58.6, to 0.59.0: https://github.com/react-native-community/rn-diff-purge/compare/release/0.58.6..release/0.59.0

**Comment by geohacker** [comment]
It looks the new version is 0.6.4. The diff is here https://github.com/react-native-community/rn-diff-purge/compare/release/0.58.6..release/0.60.4

I'll try to upgrade.

**Comment by geohacker** [comment]
Done. We're on 0.6.1 now.
