### ISSUE TITLE
Write actions and reducers to handle traces

### ISSUE THREAD

**Issue by batpad** [developmentseed/observe#101]
Toward #87 

Proposal for how we store this in the state:

```
state.traces = {
  currentTrace: {
    points: [
      {
        'lon': 79.25,
        'lat': 18.9,
        'timestamp': 3465665,
        'accuracy': ?
      }
    ]
  },
  allTraces: [
    {
      id: 'fxYgjh',
      uploaded: true,
      uploadErrors: [],
      points: [{...}]
    }
  ]
}
```

Various actions:

 - `startTrace`: Start a new `currentTrace` - do not allow action if there is an ongoing `currentTrace`.
 - `addPointToTrace`: Is called every-time a new point is captured, appends a point to the currentTrace.
 - `endTrace`: ends the current trace, moves trace to `allTraces` with `uploaded` marked as `false`.
 - `uploadTrace`: uploads trace to API, keeps track of errors
 - `uploadAllTraces`: uploads all pending traces to API, keeping track of errors on each

Action types:

```
STARTED_TRACE
ADD_POINT_TO_TRACE
ENDED_TRACE
TRACE_UPLOAD_STARTED
TRACE_UPLOADED
TRACE_UPLOAD_FAILED
```

For now, I'll work on just adding `Start Trace` and `End Trace` buttons in the settings screen to start testing the geolocation, start testing connecting to the API, etc. and we can connect it to the proper UI for it later.

I'm having a bit of a hard time thinking where best to start and end the `watchPosition` calls - this is probably best implemented as a separate service. We may want to add the `watchId` to the redux state so that the watch can be cancelled separately from where it was started. Will update this ticket if we land up doing that.

@sethvincent @geohacker @vgeorge I'll start working based on the outline above - let me know if this seems broadly sane / if there's any feedback.

One question I have is around the `accuracy` value we get back from the geolocation API. It seems like a useful metric to have, but I also don't know if it makes sense to store it along-with the trace. We can maybe just keep it on the client-side while gathering the trace, and maybe use it to decide if we should throw out any points on the trace / allow setting of some minimum `accuracy` thresh-hold that we could use when constructing the LineString to send to the API. Let me know if you have any strong thoughts around this, @geohacker @vgeorge .

**Comment by vgeorge** [comment]
The actions make sense to me.

I believe it is useful to implement accuracy filter with a "zero" threshold and store accuracy, allowing the client to send it along with the timestamps to the API server. That way we can gather some real data and perform analysis to get to an ideal threshold. Then it will be just a matter of setting a higher threshold in the app.

**Comment by geohacker** [comment]
This is pretty much done in #104
