### ISSUE TITLE
Create service to talk to Observe API

### ISSUE THREAD

**Issue by batpad** [developmentseed/observe#102]
We have a service to handle all API calls to the OSM API for data fetching and editing actions: https://github.com/developmentseed/observe/blob/develop/app/services/api.js

We probably want something similar for talking to the Observe API, where we also abstract away common parts like sending the authorization headers, etc.

The first problem is a naming problem :-) - the existing OSM API service is already called `services/api.js`. Should we rename this to `osm-api.js` and create a new `observe-api.js` - or leave the current one as is and create a separate service for the Observe API? I would rather just do the rename right now to avoid confusion in the future.

cc @geohacker @vgeorge @sethvincent - any thoughts? I will probably start stubbing out the methods we need in this service as I'm writing the actions and reducers for the traces as part of #101 and we can start filling it in once the API methods are implemented, @vgeorge .

**Comment by sethvincent** [comment]
Renaming the existing api service to osm.js or osm-api.js sounds like a good idea.

**Comment by geohacker** [comment]
👍 for renaming now.

**Comment by geohacker** [comment]
Service is now created.
