### ISSUE TITLE
Use presets from h2geo

### ISSUE THREAD

**Issue by nlehuby** [developmentseed/observe#107]
Can you consider using [h2geo project](https://github.com/jawg/h2geo-presets) for the presets ?

The project defines a format to describe a preset and maintains a list of community presets.

They are in use in [OSM Contributor](https://github.com/jawg/osm-contributor/) mobile app for instance to organize thematic mapping parties and Observe could be used with the same purpose.

**Comment by geohacker** [comment]
Hi @nlehuby, thank you for the suggestion. I think we will continue using the iD style presets for now and revisit this at another time. Keep up the good work!
