### ISSUE TITLE
Implement authentication to the Observe API

### ISSUE THREAD

**Issue by batpad** [developmentseed/observe#113]
Allow the user to login to the Observe API, and store the authentication token returned from the API in the application state.

My idea for this is:

 - Open user's web browser to something like `https://<observe-api-url>/login?redirect=observe://api-login`
 - The user will go through the authentication flow in the browser and be redirected back to `observe://api-login?token=<token>`
 - Using `Intents` and and the react native `Linking` module, this link will be registered to open back in the app.
 - We register a callback function in the app for this URL, and then read the URL, parse out the token, and store it in the state.

I was playing around to try and verify that the Intents and Linking was working (on Android) with this commit: https://github.com/developmentseed/observe/commit/f68c2852841ea5d02b5a8e1eff3af2475dd174a2 - unfortunately, my callback was never getting called when trying to simulate the URL callback event. I need to dig into this a bit deeper, it's a slightly weird one to debug.

I tried looking at the `preAuth` code which does something similar - I have some ideas for debugging this further. Hopefully the overall plan seems sane.

React Native Linking docs: https://facebook.github.io/react-native/docs/linking

**Comment by geohacker** [comment]
This is done.
