### ISSUE TITLE
ios: keyboard still shows after saving changes to a feature

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/observe#125]
On ios if a keyboard is still open when saving changes to a feature, the keyboard will still show when redirected back to the Explore screen. This seems to only happen when not entering a changeset comment.

This is especially difficult to deal with if it is a number keyboard, which (on my device at least) doesn't have a button to close the keyboard. The regular keyboard at least has the return button that can be used to close the keyboard.

The main way to manually work around this is to entire a changeset comment and then that keyboard will automatically close.

**Comment by geohacker** [comment]
This is fixed
