### ISSUE TITLE
Handle Observe API token expiry on the client

### ISSUE THREAD

**Issue by batpad** [developmentseed/observe#132]
We need to gracefully handle the case of when the user's API token has expired / is no longer valid for some reason, and then either inform the user that they need to login again, or automatically redirect them to the login page.

Initially, a question for @vgeorge : Does the API distinguish between `Unauthorized` responses and `Token Invalid / Expired` responses - i.e. on the client, I want to have a reliable generic way of knowing the difference between: `Your token is valid, but you do not have permission to do this action` and `Your token is invalid or has expired` - is the current behaviour that both of these would raise 401 errors? Is there a good way to distinguish between them?

Then, from a UI perspective, I'm not clear on what the best approach should be, especially given the fact that a lot of these actions maybe happening in the background for the user - i.e. uploading traces when the user gets online - it maybe really jarring / weird to have the app automatically redirect the user to the login flow in this case. We may rather just want a notification message and maybe an indicator to the user that they are no longer logged in to the Observe API.

 In terms of implementation, we can probably do some generic handling in the `callAPI` function that all methods go through to call the Observe API: https://github.com/developmentseed/observe/blob/9e1599d12e6397c19ec1c83319aefbbee076fc37/app/services/observe-api.js#L44 . Currently, the `callAPI` function and observe api is not passed the `dispatch` object and hence can't fire actions directly. I was hoping to avoid this as it seems much cleaner to not have actions being fired inside the API service, but it does seem like passing in the `dispatch` object may make this easier to handle inside `callAPI`.

Will be good to discuss this a bit - the implementation probably depends a little bit on how we want to handle the UI for token expiry.

cc @geohacker @vgeorge @LanesGood @sethvincent

**Comment by LanesGood** [comment]
@batpad I'm confused on which API call is in question. 

I think a more standard pattern would be to:
- Require a login for the Observe app itself, which provides the Observe service API token for that session
- When logged in, require a OSM login for editing OSM. This serves the OSM API token for that session.
- If a user doesn't want to connect their OSM login, they can proceed with just traces and photos, but UI is needed - both a notification modal for refusing OSM connection, a settings switch/toggle to indicate that this is unconnected, and perhaps even a status bar similar to the Offline status bar
- alert a user to the need for an OSM login any time they try to edit the map
- if a user's keys expire during offline use, require both logins with proper notifications when reconnecting with traces/photos/OSM objects in the upload queue 

The above would require the user to login again to the Observe app any time their Observe API token expires. Does this make sense given the current API setup?

**Comment by LanesGood** [comment]
### Login flow discussed in scrum:
- Both logins are contained on the account page
- Status bar needed for indication of user's login status

Self-assignment: create screens for new Account page, status bar, and notifications of token expiry

**Comment by LanesGood** [comment]
@batpad please see the three updated screens below:

https://invis.io/CGUB4COZKTB#/394194010_explore--token-Expired

One other potential notification could be on the "Your contributions/traces/photos" screen - but can this simply be text with the reason as pending being "reconnect your OSM account/the Observe API to complete upload"?

**Comment by geohacker** [comment]
This is done!
