### ISSUE TITLE
Associating photos to features

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe#137]
In #136 we'll introduce functionality for users to add photos to existing features. In case these features don't have a valid OSM ID, we have to figure out what's the best way to upload them to the Observe API. There are two ways to do this:

1. Upload the photo and feature independently 
This would mean that we will have to make an additional patch request to the API to update the photo with the OSM feature ID once that's done.

2. Upload the photo after the feature is uploaded successfully 
This means that if a photo is associated with a feature that has a temporary Observe ID, we will hold off from uploading the photo to the API until the feature is uploaded. Once the feature is uploaded, we'll update the photo on the app and then submit to Observe API.

@developmentseed/observe thoughts? I think I'd be inclined to implementing 2.

**Comment by LanesGood** [comment]
@geohacker I'd vote for option 2 as well. If necessary, we could add a note on the "Your Photos" screen, which shows pending photo uploads, that says "waiting for associated feature to upload" or something similar to indicate the reason for the hold.

**Comment by geohacker** [comment]
This is done #150
