### ISSUE TITLE
Can photos have directionality?

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe#138]
For future enhancement, a question from potential users: do photos have directionality? For photos that are not associated with features, a light direction cone indicator on the map could help orient users viewing their photos. Directionality also may help with future uses of photos and associated plugins/JOSM editing.

**Comment by vgeorge** [comment]
The current data model for photos already includes bearing.

**Comment by vgeorge** [comment]
My comment was incomplete, is bearing sufficient or the data model should include other parameters for directionality?

**Comment by geohacker** [comment]
We do capture the `heading` for the current location where the photo is taken. Will store this in the API.

**Comment by vgeorge** [comment]
@geohacker do we need to rename `bearing` for `heading` at the API?

**Comment by geohacker** [comment]
@vgeorge If it's not too much trouble, yes. The location module on the phone by default calls it `heading`.

**Comment by vgeorge** [comment]
For the record, this was implemented at the API in https://github.com/developmentseed/observe-api/pull/38.

**Comment by geohacker** [comment]
We're storing directionality now.
