### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by batpad** [developmentseed/observe#16]
Creating a master ticket for missing tests - we can break these down into smaller tickets, etc. Just wanted to make some notes while things were fresh.

### Actions / Reducers

 - [x] New synchronous actions and reducers: few of the ones added later don't have tests. These should be pretty quick. 
 - [x] Comprehensive test for `uploadEdits` and handling different errors by mocking the API. Would be good to do #242 first.
 - [ ] Tests for Offline Tiles / caching logic -- it would be great to have a few tests for testing the logic in actions / reducers dealing with offline tiles, caching, expiry, etc. cc @mojodna 

### Utils

 - [x] Some of the stuff dealing with presets can maybe get a few tests?
 - [x] The `edit-utils` needs tests

### Components

It would definitely be nice to have tests to test component actions, stuff like button presses, etc. - and probably jest snapshot tests for different states of render of components. This one is probably a bit of work since we have almost no component tests right now. @sethvincent if you have any notes / thoughts / examples, let know - there's some stuff like the UserContributionItemScreen where it would definitely be nice to have some basic tests to test what it renders based on different props and state, for example.

@geohacker @sethvincent @mojodna - please add to this list / make separate tickets for any tests that are missing that you feel strongly about.

**Comment by geohacker** [comment]
I sprinted on writing tests for most of the parts. The most important one that's pending now is the offline map download and cache eviction workflow. I'll start looking at that next. 

I think it might be good to also do some snapshot tests for the UI.

**Comment by batpad** [comment]
@geohacker the new tests all look great - feel free to close this issue and open a separate issue that's focussed on Component / UI Snapshot testing.
