### ISSUE TITLE
Storing nodes and identifying relations

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe#168]
To enable #91, we've to store all member nodes and identify if ways are part of relations. The premise here is that we won't allow editing geometry of ways that are part of relations -- so protect them from causing validation problems. 

I spoke to @batpad and here's an approach that may be less intensive. 

1. Get nodes as an output of osmtogeojson for lookup
We've some [work in progress](https://github.com/geohacker/osmtogeojson/pull/4), adding an option to osmtogeojson to get all the nodes as part of the geojson. We'll make this output separate from the feature geojson and a second output of osmtogeojson which can be directly imported to async-storage for the nodecache.

2. Get a map of features to check if they are part of relations
We don't need resolved relation geometries. A way to lookup whether the feature in question is part of a relation is all that's required for the current usecase. This can be achieved by parsing the relations and creating map, but avoiding geometry resolution for performance reasons.

cc @sethvincent @batpad

**Comment by batpad** [comment]
Got a rough sketch of this idea here: https://github.com/geohacker/osmtogeojson/pull/5 - this should work to test by sending osmtogeojson a `mapRelations` option set to `true`, and you will get back an object with `geojson`, `featuresInRelation` and `nodes` as separate keys. We should probably name all these things a bit better.

**Comment by geohacker** [comment]
This is work in progress #170
