### ISSUE TITLE
Way editing mode details

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe#172]
I discussed with @batpad on a few specifics of the way editing mode actions and data structure. Doing a brain-dump here.

### Entering the way editing mode
Like POI editing, way editing should also need an explicit state to say that the user is now editing the geometry of a way. For a way that's being edited, we would load all member nodes and display.

### Storing geometry editing actions
Each node move or delete will be atomic actions on the geometry. This is the best approach because then we can send changesets for the nodes in question. Deleting a node would need to have a changeset at the way level to remove the membership.

Each actions (move, delete, add) would be stored in the state. Along with old and new state of the node in question. The action store will allow is to implement undo/redo as well as generate the final representation of the way for visualization.

### Visualizing geometry changes
Once the editing is done, we'll use the action store to prepare the new representation of the edited way to display on the map (if offline or until the changeset is uploaded). Once the changeset is uploaded, the tiles would refresh and map state is updated.

### Creating changesets
* For moving or adding attributes to member nodes, changeset is only needed for the node
* For deleting or adding new member nodes, changeset is required for both the node and the way

@developmentseed/observe

**Comment by LanesGood** [comment]
@geohacker does this affect any of the UI proposed in the [Invision prototype](https://invis.io/CGUB4COZKTB#/389042808_explore--main)? I think the pop-up of a way editing contextual menu will provide the necessary signifier to users that way editing mode is active. Undo and Redo are included in this menu as well.

The main question would be whether or not we want to specify nodes vs. ways in changesets with a UI beyond simple text notifications. This could be with an icon and/or color pattern that is different from the normal changeset message UI. Is this needed?

**Comment by geohacker** [comment]
@LanesGood the proposed UI aligns well with the states I've outlined above. I think it might be useful to distinguish nodes and ways in the changeset. We could use icons perhaps.

**Comment by batpad** [comment]
@geohacker here's a rough sketch of how the data structure for a new `way-geometry-edit` reducer or so could look like:

```
{
  currentWayEdit: {
    wayId: 'way/12345', // or should this be an integer id?
    nodes: [
      {
        id: 'node/12345', // again, should this be an integer id?
        hasTags: false, // boolean, @geohacker - it maybe useful here to know whether the node has tags or is an orphaned node?
        isDeleted: false, // set to true if user deletes node
        coords: [1.0, 2.0], // lng, lat
        newCoords: null // null or array with lng, lat 
      },
      {
        ...
      }
    ],
    actions: [
      type: 'add', // add, move or delete
      data: {}
    ]

  }
}


ACTIONS:

 - WAY_EDIT_MOVE_NODE
    - nodeId
    - newCoords

 - WAY_EDIT_ADD_NODE
    - position // position to insert new node at (should this be node id new node should be inserted after?)
    - coords

 - WAY_EDIT_DELETE_NODE
    - nodeId

 - WAY_EDIT_UNDO

 - WAY_EDIT_REDO
```

The mechanism for Undo / Redo is not super clear, and that data structure might change a bit, we also might need another variable to store the redoActions when someone does an Undo.

The other thing I'm not sure is if this data structure also includes tag changes made to the way, or can this just be focussed on geometry editing?

Also, I think this structure should work for both new ways as well as editing existing ways, but we should probably think it through.

If this broadly looks okay, I can start sketching out the relevant actions and reducers.

**Comment by batpad** [comment]
Minor question: is Undo / Redo only for things that affect the state of the way - i.e. things like move node, add node, delete mode, or does it also affect selections, for eg. if I "Select" a node, and then hit Undo, does it just Unselect the node, or does it undo my previous operation that affected the way?

Similarly, if I go to "next node", just undo just take me back to the "previous node" or does it Undo my last way operation?

@LanesGood any thoughts?

**Comment by LanesGood** [comment]
@batpad I would expect that undo/redo acts only on constructive/destructive actions that affect the way. 

I'm still unsure whether next/previous is a good or necessary feature. One suggestion I included in the mockups here is that next/previous only appear in the way editing mode, so it is not possible to express these actions in new way creation mode. See this screen in InVision: https://invis.io/CGUB4COZKTB#/404077939_edit-Way--move-Node_Copy

**Comment by geohacker** [comment]
> I'm still unsure whether next/previous is a good or necessary feature. 

@LanesGood I'd say this is not entirely necessary to implement. I'm having a hard time thinking how much a user would find this useful. It's always been easy to think that the user can select whichever node they are interested in by pressing. We would want to make sure this selection is possible by making the style of the node clear enough.

**Comment by geohacker** [comment]
We're much ahead of this. Edit actions are all implemented.
