### ISSUE TITLE
Latency in selection of feature

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/observe#175]
When selecting a feature to edit, there is inconsistency in the time it takes to show that the feature is selected. 

Wait times vary from 1 -> 5 seconds

Example: User wants to edit a building's tags, touches building, needs to wait several seconds before it shows it is selected.

**Comment by sethvincent** [comment]
We've discussed previously that this is likely due to osmtogeojson still processing data after a fetch.

**Comment by geohacker** [comment]
#181 addresses these. Closing for now.
