### ISSUE TITLE
Overlapping text on preview pane

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe#188]
When pressing on a mapped area that also contains a POI marker, the labels of both the area and the POI are displayed hierarchically on the preview pane IF the POI is clicked first. 

However, if the area is clicked first, and then the POI contained within the area is clicked, the text of both labels is displayed overlapping as seen in the below screenshot.

OS: Android
Device: OnePlus 5
Build: `observe-v0.2.0-build-12-release.apk`
Install Date: 2/13/20

![Screenshot_20200213-122525](https://user-images.githubusercontent.com/12634024/74950671-75530e80-53cd-11ea-94e7-a2e347182dbc.jpg)

**Comment by vgeorge** [comment]
Fixed by #254.

**Comment by geohacker** [comment]
Fixed further in #314
