### ISSUE TITLE
Script to prepare map icons

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe#194]
We rely on maki and temaki icons to render features on the map. These icon packages get regular updates along with new presets. We should write a script to:

* fetch a release
* convert the svg to pngs
* and drop to the observe assets folder

**Comment by geohacker** [comment]
This is probably not that straightforward. We need to first make them fill white with transparent background, and then convert to svg. Previously @ricardoduplos may have done this with Illustrator batch operations. 

cc @LanesGood @batpad @sethvincent

**Comment by geohacker** [comment]
@ricardoduplos told me a trick that we could add `fill='#fff'` to the svg path to turn it white before converting. So now I can do something like `sed -e "s/<path /<path fill='#FFF' /" aerialway-11.svg | convert-svg-to-png --height 64 --width 64 > aerialway.png`

**Comment by sethvincent** [comment]
@geohacker was this resolved by #193?

**Comment by geohacker** [comment]
@sethvincent yes it was. Closing.
