### ISSUE TITLE
create way editing menu component

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/observe#197]
create the way editing ui component that sits at the bottom of the screen while in way editing mode.

<img width="362" alt="Screen Shot 2020-03-05 at 12 47 10 PM" src="https://user-images.githubusercontent.com/164214/76024216-93e1fb00-5edf-11ea-8744-68ca9710d5fb.png">

**Comment by LanesGood** [comment]
@sethvincent I thought we decided that we would not implement the "prev node" and "next node" buttons - the left/right chevrons immediately adjacent to the "add node" button. @batpad @geohacker is this correct?

Also, the latest version of collecticons includes a new `arrow-move` icon for this toolbar, and `circle-record` for the megamenu/record toolbar.

**Comment by geohacker** [comment]
@LanesGood @sethvincent yeah that's right, we don't want to implement the next node - prev node functionality right now.

**Comment by sethvincent** [comment]
this is closed by #198.

future work involves wiring it up with the appropriate actions: #201
