### ISSUE TITLE
refactor getFieldInput function to allow way fields

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/observe#210]
The current check for supported field types doesn't allow for some fields associated with ways. Example errors:

```
 LOG  [Error: Unsupported field type: onewayCheck]
 LOG  [Error: Unsupported field type: maxspeed]
 LOG  [Error: Unsupported field type: structureRadio]
 LOG  [Error: Unsupported field type: access]
 LOG  [Error: Unsupported field type: onewayCheck]
 LOG  [Error: Unsupported field type: maxspeed]
 LOG  [Error: Unsupported field type: structureRadio]
 LOG  [Error: Unsupported field type: access]
```

The check for supported field types is here: https://github.com/developmentseed/observe/blob/fe488e90c302f79778939ae71084aeb4efa4811c/app/components/Input.js#L426-L4644

**Comment by geohacker** [comment]
This i s done https://github.com/developmentseed/observe/pull/215
