### ISSUE TITLE
Way area tags and geometry transformation

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe#218]
When adding a new way or editing an existing way, we need to transform the geometry based on the preset that's selected. Presets have a geometry field that has all compatible geometries. This is what we will use to display applicable presets for a feature. 

To transform and render the feature geometry, we'd want to use https://github.com/osmlab/id-area-keys. 

cc @developmentseed/observe

**Comment by geohacker** [comment]
I think we should use what iD is doing currently https://github.com/openstreetmap/iD/blob/develop/modules/osm/tags.js#L17, instead of that module. 

@vgeorge could this be something you can look at?

**Comment by vgeorge** [comment]
This was addressed at https://github.com/developmentseed/observe/pull/227.
