### ISSUE TITLE
Ability to delete ways

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe#233]
Pressing the "delete" button in way editing mode results in a bug. It looks like the delete button is not currently wired up fully.

Update:
`Delete` works properly when a node is selected. When a node is not selected, the app throws th below error.

![image](https://user-images.githubusercontent.com/12634024/82606261-c9b08a80-9b84-11ea-8747-c5440dc861c7.png)

**Comment by LanesGood** [comment]
I'm not able to reproduce this in the latest version of `edit-ways` - please test to confirm before closing.

**Comment by sethvincent** [comment]
This was fixed as a side-effect of the features-in-relation branch #221.

**Comment by vgeorge** [comment]
I tested deleting nodes and ways on Android and iOS, both worked without errors.
