### ISSUE TITLE
Disable way editing buttons when states are not yet active

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe#234]
Consider disabling the "Delete" "Undo" "Redo" and "Move" buttons in the way editing contextual menu by default, and activating them only by the respective actions below:

![image](https://user-images.githubusercontent.com/12634024/82606891-d5508100-9b85-11ea-9799-6a4c19f1cd1a.png)

| Button | Enabling Action| Disabling action |
| -- | -- | -- |
| Delete | After node selected | No node selected |
| Undo | After first node added | All actions undone |
| Redo | After action undone via "undo" | No actions undone via "undo" |
| Move | After node selected | No node selected |

Consider styling the disabled state for buttons with reduced opacity, and removing touchable functionality from button. 

For future enhancement, consider adding tooltip on button touch when disabled to hint enabling feature to user.

**Comment by vgeorge** [comment]
This was implemented by #262. There is a minor bug in the "Undo" button. When the edit way screen is first opened, the button is enabled like a command was already executed, which is not the case. This happens because wayEditingHistory.past is not empty.

**Comment by geohacker** [comment]
I captured the pending item in this ticket in #304. We can close this and track #304 outside of the milestone.
