### ISSUE TITLE
Broken item list after consecutive selects

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe#241]
How to replicate:

- Click nearby slightly overlapping features, generating a list with at least two items in the drawer
- Click in another existing feature

The resulting list is blank in iOS and scrambled in Android.

## iOS

![bug-1-ios](https://user-images.githubusercontent.com/329694/82668796-2322c300-9c32-11ea-9ab0-26dba2b53291.gif)

## Android

![bug-1](https://user-images.githubusercontent.com/329694/82668835-36359300-9c32-11ea-999d-bb7f55294900.gif)

**Comment by LanesGood** [comment]
Also ticketed here: https://github.com/developmentseed/observe/issues/188

**Comment by vgeorge** [comment]
🤦‍♂️

**Comment by vgeorge** [comment]
Reopening this as the cause might be the same, but replication procedure is different.

**Comment by vgeorge** [comment]
Fixed by #254
