### ISSUE TITLE
Add way state isn't cleared after exiting the mode

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe#242]
Steps to reproduce:

1. Select add way mode
2. Draw some nodes
3. Click the tick 
4. Select a feature type
5. Then hit back and go back to Explore mode
6. Select add way mode again
7. Draw a node, notice that the node is started from the previously drawn way. Expected: new way.

cc @sethvincent

**Comment by sethvincent** [comment]
i wasn't able to reproduce this exactly. what i'm seeing now on the edit-ways branch is that when i press the back button from the preset or fields views the state is cleared while still in the add_way mode. not quite the same as what you describe and still not the intended behavior.

**Comment by vgeorge** [comment]
@sethvincent I think I was able to replicate what your described and opened https://github.com/developmentseed/observe/issues/249.

**Comment by geohacker** [comment]
I wasn't able to reproduce this one. So let's close here for now.
