### ISSUE TITLE
issues noticed testing changesets branch

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/observe#255]
Much of this isn't necessarily related to the changesets branch, but came up while testing out that branch:

- [ ] when moving a node in a linestring, the node style moves but the line style does not
- [x] after editing a way geometry, user can't save the feature until they edit a tag value. we should allow save after just editing the geometry
- [x] `movedNodes` property should be hidden from field editing view
- [x] after editing a tag to get around the previous bug, when saving the changeset i get `TypeError: Cannot read property 'find' of undefined` in the logs, without a clear stacktrace. i noticed that `allEdits` in the `uploadEdits` action is an empty array, which doesn't matter for that specific error message, but is potentially interesting.
- [x] way editing state does not seem to be clearing fully. after editing a way, going back to explore without saving, and then starting to add a way, the previously selected way i was editing is still selected

i can make issues for each of these tomorrow if needed

**Comment by geohacker** [comment]
Fixed all of the above expect the first one. Ticketed that separately #257
