### ISSUE TITLE
Make it evident that one can search for presets

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe#27]
The search can perhaps have a placeholder text to say ' Search for more presets...'

**Comment by batpad** [comment]
Possible also rename `Point` to `Point without preset` or `Point without tags` to make it more clear what that is - i.e. it is not "Select type" and then get to a screen to select preset -- since we only allow adding of a single type, i.e. points.

**Comment by geohacker** [comment]
Yeah that makes sense. Perhaps we should expand that default list of Building, and Point to include more commonly used presets.
