### ISSUE TITLE
Nodes added to way show up south of crosshair position

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/observe#275]
Bug report about nodes in a way not showing up at the same position as the crosshair:

> I had the cross hairs on the middle of the screen as so, pressed the + and the red point was added several meters below it. I assumed it would be adding at the center.

![Screen Shot 2020-05-28 at 10 44 16 AM](https://user-images.githubusercontent.com/164214/83175080-38836b80-a0d0-11ea-9318-62430a443a59.png)

My first guess is that the position of either the crosshair or the node coordinates is incorrect in this case because of the GPX tracing components being visible. Not completely sure about that, but it's plausible.

**Comment by geohacker** [comment]
I'm able to reproduce this one.

**Comment by geohacker** [comment]
Confirmed that this is because of the `RecordHeader` component. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/371666/83258686-5803bc80-a1d4-11ea-9b96-749c822e3abf.gif)

**Comment by geohacker** [comment]
Fixed.
