### ISSUE TITLE
Remove feature from the map after deleting

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe#277]
When the app is offline it allows editing already deleted features that were not uploaded. How to replicate:

- Start the app connected to the internet
- Choose an existing node/way
- Turn off any network access (enter flight mode)
- Delete the selected node and confirm

The feature will be still available in the map for editing, causing a conflict when the user does additional changes to it.

**Comment by geohacker** [comment]
cc @batpad

**Comment by geohacker** [comment]
This is fixed in #284
