### ISSUE TITLE
Title overflow in feature detail view

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe#278]
How to replicate:

- Go offline
- Add a node or a way, confirm
- Select it and enter detail screen from the drawer

New features have long ids and title will overflow to navigation icons. I believe there are two possible solutions here:

1) Change the title to "View node" or "View way" as the id is already listed in metadata fields
2) Limit title length but cutting and add ellipsis at the end, e.g.: "node-observe-y2..."

Example:

![image](https://user-images.githubusercontent.com/329694/83294811-d61c8f00-a1e5-11ea-8995-a3d406778545.png)

**Comment by LanesGood** [comment]
@vgeorge I think option 1 is best. As you point out, the name is found in the attributes, so this will help standardize the view across points with long and short names, and for those nodes/ways which are missing names.

**Comment by geohacker** [comment]
Option 1 sounds good to me!

**Comment by geohacker** [comment]
This is done in #284
