### ISSUE TITLE
Selection of ways that are lines that pending upload

### ISSUE THREAD

**Issue by karitotp** [developmentseed/observe#286]
When a new way is added and it is tagged as highway, fence or whatever that is a line, it can not be selected, as the other features like points or polygons, when it is pending to upload.
This only happen when the feature is not upload yet.

Steps to replicate: 
 
- Add a way.
- Tag as highway or fence (not upload  it).
- Try to select the feature (the way will not be selected).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11504548/83543737-7b738380-a4c2-11ea-9109-99a008debcb2.gif)

**Comment by geohacker** [comment]
Thank you @karitotp. We are tracking this issue in #285
