### ISSUE TITLE
App loses map state when in background

### ISSUE THREAD

**Issue by batpad** [developmentseed/observe#3]
Steps to reproduce:

  - Pan map to a location
  - Switch apps on phone
  - Go back to Observe

Expected behaviour:

 - Map should be at the same location I was at when I switched out of the app

Actual behaviour:

 - Map resets to initial location

This should be fairly straightforward to deal with when we are hooking up things into persistent storage, we probably want to store the current map location as well and take the user there if they come back to the app.

**Comment by sethvincent** [comment]
I haven't been seeing this behavior since our react-native upgrade and switch to @react-native-mapbox-gl/maps. So far I've tested on an android device and an ios device.

**Comment by sethvincent** [comment]
I take it back. It can still happen. I think it depends on how long the app is in the background.

**Comment by geohacker** [comment]
I've not been able to reproduce this on iOS. I think it depends a bit on the device and the settings -- especially if the user has asked to reduce background running apps. I think we should close here and revisit if this becomes more of a concern to usability.
