### ISSUE TITLE
Some actions in the geometry edition is stopping the app

### ISSUE THREAD

**Issue by karitotp** [developmentseed/observe#312]
The edition of a way is allowing to the user to add new points outside of the edited way (instead of only allow to add new nodes on the way or move nodes of the way). In this case the app works correctly because it is not recognizing any edition, even if in addition to add point outside of the way and also move the nodes of the edited way or add new nodes to it, the app save correctly the edition
without consider the additional points added outside the way.

The problem is when those additional added points outside of the edited way, is added as a new node to another way, if we move the pointer to add new points over another way, this way is appearing as selected for geometry edition and it allows us to add new nodes to this way. This action is doing that the app stop to work when we want to save this type of changes. Showing the message "Observe has stopped"

![Screenshot from 2020-06-08 12-47-05](https://user-images.githubusercontent.com/11504548/84063163-33eb6c80-a986-11ea-9ae8-24d786c45a55.png)

Also, actions like add points outside the edited way and then change an attribute of the way, is breaking the app.

**Comment by geohacker** [comment]
Thank you for reporting this @karitotp. This is indeed a problem, in the edit way mode, we shouldn't allow adding nodes outside of ways.

**Comment by geohacker** [comment]
This should be fixed by #316
