### ISSUE TITLE
New nodes in existing ways persist after deletion in editing mode

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe#321]
Adding new nodes to existing ways and then deleting these and surrounding nodes results in strange behaviors. Most of the time, these new nodes are still rendered even when the resulting way is altered. This is difficult to describe exactly how to reproduce, as I'm not sure what exactly is happening. Noting as well that I'm purposefully trying to break things, rather than reproduce a live use case.

![new-node-delete-issue](https://user-images.githubusercontent.com/12634024/84227645-f46e6e80-aab2-11ea-9a00-a8a7e3afcf11.gif)

The final result after attempting to save the changeset is also usually a `console.error:"Error storing data", Error: database or disk is full (code 13 SQLITE_FULL)` - this is on Android AVD,

This seems related to #289 #296 and #318

**Comment by LanesGood** [comment]
EDIT: Far less complex example indicates that this behavior is a consistent bug
![new-node-delete-bug](https://user-images.githubusercontent.com/12634024/84227993-d2c1b700-aab3-11ea-9838-6e973da6a23e.gif)

**Comment by geohacker** [comment]
@LanesGood nice catch. I think I know what could be going on here. The node itself is deleted from the feature (notice the change in the shape) but it's not hidden from the map because of a style filter issue. I can fix.

**Comment by geohacker** [comment]
> console.error:"Error storing data", Error: database or disk is full (code 13 SQLITE_FULL)

This is unrelated to the nodes not getting deleted. This likely means the AVD hit the limit for async-storage. A reset should fix it.

**Comment by geohacker** [comment]
This is fixed in #322
