### ISSUE TITLE
OSM login issue on iOS

### ISSUE THREAD

**Issue by smehenni** [developmentseed/observe#327]
I can't login into my OSM account via Observe, I get the "Sorry, could not log in with those details message". I double checked my password and could login in a different safari tab, but strangely not via the button in Observe.

**Comment by geohacker** [comment]
@smehenni are you trying to login with your credentials for the main OSM instance? Observe uses the OSM dev instance, mostly because we're looking to get more feedback. You should create an account at https://master.apis.dev.openstreetmap.org/

**Comment by smehenni** [comment]
@geohacker woops, yes I was. Created an account on the dev instance and it's working, I should have asked. Closing.
