### ISSUE TITLE
transition to @react-native-mapbox/maps

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/observe#33]
Looks like development of react-native-mapbox-gl has moved to https://github.com/react-native-mapbox/maps

@react-native-mapbox/maps uses more recent versions of the mapbox sdk and may resolve map usability issues like the flickering we see when panning (#25).

We probably shouldn't switch until this issue on react-native-mapbox/maps is completed: https://github.com/react-native-mapbox/maps/issues/31

Making this switch also depends on upgrading to react-native@0.59 (#1)

**Comment by geohacker** [comment]
This is done, finally!
