### ISSUE TITLE
Logging into OpenStreetMap

### ISSUE THREAD

**Issue by eneerhut** [developmentseed/observe#34]
This might be an OSM issue, but I can't seem to login with my OSM credentials. The exact same credentials work fine to log into OSM directly and through other apps then need OSM OAuth.

Any ideas?

![Screenshot_20190521-164027_Chrome](https://user-images.githubusercontent.com/11349863/58074043-8cb75e00-7be7-11e9-9d2c-3fa9fa2ee75a.jpg)

**Comment by geohacker** [comment]
@eneerhut thanks for the ticket! Yes that's right. This version of Observe is configured to work with the OSM test API. So your login with the main OSM instance will fail.

To create an account on the test API, you can visit https://master.apis.dev.openstreetmap.org/
(more info in the diary post)

**Comment by eneerhut** [comment]
Ah rookie mistake. But thanks @geohacker, I'm up and running!

**Comment by stephan75** [comment]
So what about giving that hint inside the app before each user tries to log in with normal OSM credentials?
