### ISSUE TITLE
Responsiveness issues

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe#36]
The titles and display text are not rendering correctly on my device. Is this a known issue? Should we aim to address this in the coming sprint, or save for future cycles?

**Device:** OnePlus 5 
**Screen Size:** 5.5"  (13.97 cm) 
**Resolution:** 1080 x 1920 
**OS:** Oxygen 9.0.5 on Android 9

![Screenshot_20190610-220552](https://user-images.githubusercontent.com/12634024/59224083-d1725b80-8bcd-11e9-8372-137534921b51.jpg)
![Screenshot_20190606-144611](https://user-images.githubusercontent.com/12634024/59224084-d1725b80-8bcd-11e9-9ce1-e4b65de6981d.jpg)
![Screenshot_20190606-144600](https://user-images.githubusercontent.com/12634024/59224085-d20af200-8bcd-11e9-83f0-ba7128528c43.jpg)
![Screenshot_20190606-144415](https://user-images.githubusercontent.com/12634024/59224400-8c025e00-8bce-11e9-95b9-e0ae4b421b5a.jpg)

**Comment by sethvincent** [comment]
I wonder if this is related to #14

**Comment by LanesGood** [comment]
@sethvincent Thanks for pointing to that. The comments on https://github.com/facebook/react-native/issues/15114 indicate that this is common for my device type. Once I switched back to Roboto instead of the device default font the text rendered correctly. This seems limited to Oppo/OnePlus devices in the issue, but I'd agree that Roboto be packaged as suggested.

**Comment by LanesGood** [comment]
Closing, will keep limited instead to #14
