### ISSUE TITLE
Can't go back to feature list to reselect point type

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe#55]
This appears to be a bug. I've reproduced the behavior on my Android phone and on a local copy in Android emulator. To replicate:
- Add a point in Explore
- Select a feature type
- Hit the "back" arrow

**Expected behavior**: return to "Select Feature Type" screen to reselect type
**Actual behavior**: returns to "Explore" screen, with crosshair still set

This may be related to #5. If returning to "Explore" after pressing `back` is intentional, the point should be unselected. However, this seems like unexpected behavior from the back button, as it skips a step. The back button should match the expected behavior above.

**Comment by geohacker** [comment]
Fixed in #79

**Comment by LanesGood** [comment]
@geohacker fyi this bug cropped up for me again on recent testing. It occurs - occasionally - on the branch for PR #140. I'm not sure of the exact steps to reproduce, but wanted to draw your attention to it in case you also experience the issue again.

**Comment by geohacker** [comment]
@LanesGood I've not seen this so far, but will keep an eye!
