### ISSUE TITLE
separate icons for map & ui

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/observe#57]
We're currently reusing icons that are used in the map for the ui. This limits us to white png icons.

Adding an additional png icon set in the primary blue color would make it possible to do #52.

Or we can use svg icons, though that would require an additional dependency (https://github.com/react-native-community/react-native-svg) and svg icons may not work great on the map.

I'm currently exploring using svg icons and if that doesn't work will fall back to adding blue png images.

**Comment by LanesGood** [comment]
@sethvincent I think SVG for the whole app is the best bet. If we're limited to PNGs, we could weight the size <>dependency tradeoffs between adding a second icon set and using a library like the one linked here to use CSS-like filters on the PNGs:
https://www.npmjs.com/package/react-native-color-matrix-image-filters

**Comment by sethvincent** [comment]
After a bunch of trial and error I made some progress getting svg files working. In the morning I'll try this other module along with react-native-svg and I as long as it works alright should fit our needs for ui icons: https://github.com/vault-development/react-native-svg-uri

I'd like to stick with png for the map icons for now to make things easier, and then come back to using svg on the map as a separate issue.
