### ISSUE TITLE
Switching layers takes me to my current location

### ISSUE THREAD

**Issue by batpad** [developmentseed/observe#6]
Steps to reproduce:

 - Navigate away from your current location on the map
 - Click layer switcher, switch layers

Expected behaviour:

 - Layer should change and I should remain wherever I currently am on the map

Actual behaviour:

 - After switching layers, map pans me back to my current location marker.

cc @geohacker

**Comment by geohacker** [comment]
This doesn't seem to be an issue anymore, after the Mapbox GL upgrade.
