### ISSUE TITLE
TypeError: error.toJSON is not a function

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe#63]
Comes from https://github.com/developmentseed/observe/blob/54975415f447792f581fb53bbed24c24944bdefd/app/actions/edit.js#L80

The error object is different from Observe's error object

Steps to reproduce:
1. Make an edit without logging in
2. Upload
3. See console for warning

cc @batpad @sethvincent

**Comment by batpad** [comment]
Grr this should ideally never happen since we should catch all errors and make them subclasses of ObserveError -- but we should probably do some handling here to handle the case where the error is NOT an `ObserveError` but some error that has propagated through.

**Comment by sethvincent** [comment]
should this be closed by #70? it's mentioned there but didn't have "fixes" directly in front of it so didn't auto-close.

**Comment by geohacker** [comment]
@sethvincent yes this can be closed.
