### ISSUE TITLE
Support for GPS tracking

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe#87]
Allowing the users to turn on location tracking and record GPS traces will make it easier to create ways, and also do analysis on overall mapping miles. 

React Native has a few ways to do this, I'll list them and pros and cons here.

Library | Pros | Cons
--------|-----|-------
react-native-maps | easy to integrate | have to write integration code and processes, no background recording
[react-native-background-location](https://www.npmjs.com/package/react-native-background-geolocation) | supports background, battery efficient, detect type of activity, support for sqlite storage | android is $299 license fee
[mauron85/react-native-background-geolocation](https://github.com/mauron85/react-native-background-geolocation) | supports background | seems a bit unreliable reading the docs
[react-native-radar](https://github.com/radarlabs/react-native-radar) | supports background, part of a paid sdk so maintained, free (?) | have to integrate the SDK
use mapbox-gl onUserLocationUpdate | no added libraries | no background, less precision 

I think I'll give  mauron85/react-native-background-geolocation a shot first and see as it is the one that can be configured to our needs easily. 

cc @sethvincent @batpad

**Comment by gmaclennan** [comment]
@geohacker for Mapeo we use [expo-location](https://docs.expo.io/versions/v34.0.0/sdk/location/), which we found more reliable that the standard React Native GeoLocation module (we don't use Expo, but you can use the expo modules as a "bare" app). Expo supports [background location updates as of the latest SDK](https://docs.expo.io/versions/v34.0.0/sdk/location/#background-location) but background tasks are [not yet supported](https://docs.expo.io/versions/v34.0.0/sdk/task-manager) for bare apps. We are waiting for this support to land before adding background tracking, since the Expo route looks like the most reliable long-term.

**Comment by LanesGood** [comment]
@geohacker I'm working on UI for traces and wanted to confirm that the following workflow looks appropriate:

**Record Track Workflow**

1. **Button**: Hit “Record Track” button
2. **Modal**: Confirm Track recording settings (Copy OSM And approach);
     - First time only? 
     - Keep in settings
3. **Modal**: Instructions appear on screen - First time use?
4. **Screen**: Recording
     - Track and location marked on screen
     - Mileage and time?
     - “Recording” and “Pause” icons
5. **Screen**: Pause recording
6. **Screen**: Finish Recording
7. **Screen**: Save Track
     - Add description

/cc @batpad @vgeorge

**Comment by LanesGood** [comment]
I've created mockups for the GPX Trace flow, and linked screens via hotspots in Invision: https://invis.io/CGUB4COZKTB. Please use the comments feature to make notes, and play around with the suggested interactivity - if you click on the screen, a blue box will appear showing you where you can click for simulated app interaction. A few of the screens in the uploaded mockups are not hotspotted - these are alternate display options for the recording menu.

Updated Workflow Per comments this afternoon in Slack:

**Record Track Workflow**

1. **Button**: Hit “Record Track” button
2. **Modal**: Confirm Track recording settings (OSM And approach);
     - First time only? 
     - Keep in settings
3. **Modal**: Instructions appear on screen - First time use?
4. **Screen**: Recording
     - Track and location marked on screen
     - Mileage and time?
     - “Recording” and “Pause” icons
     - Normal "Add Point" and other add feature menu options still available (@geohacker _is this the case? Or do we have different options available for add POI/way/photo when recording?_)
5. **Screen**: Pause recording
6. **Screen**: Finish Recording
7. **Screen**: Save Track
     - Add description
     - Discard Track

**Additional screens**
- Trace detail (preview + full) on trace click
- View all (own) traces on map
- Trace settings (in main settings screen)
- Prompt: App tracing in background, user trace exceeded max points/time, trace doesn't meet min distance/time

/cc @geohacker @batpad @vgeorge @sethvincent

**Comment by geohacker** [comment]
Pretty much done!
