### ISSUE TITLE
Observe API

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe#89]
To store GPX and photos we need a lightweight API. The API would provide the following functionality:

1. Endpoint to submit and fetch GPX traces
2. Endpoint to submit photos along with timestamp and location
3. A way to add, update and remove OSM feature IDs to photos
4. Login using OSM + 2FA
5. Basic front-end / dashboard to view and remove photos and GPX traces. Ability to import these into JOSM through [JOSM remote control](https://wiki.openstreetmap.org/wiki/JOSM/RemoteControl) 

cc @vgeorge @batpad @sethvincent

**Comment by vgeorge** [comment]
Items 1 to 4 were transfered to [observe-api](https://github.com/developmentseed/observe-api/issues) repo. I believe we can follow up them from there now.

Item 5: I've created a new repo for the dashboard [here](https://github.com/developmentseed/observe-dashboard) and added [some issues](https://github.com/developmentseed/observe-dashboard/issues). @LanesGood, I'm not sure where we are at UI/UX for the dashboard, please feel free to add your comments if I missed something.

@geohacker I believe we can close this.

**Comment by LanesGood** [comment]
Should the API also clone or somehow mirror a user's added POI's and ways? This would allow the API Dashboard to become a much more of a robust web application for tracking and exposing the entire Observe ecosystem. I can imagine this wouldn't be as desired for a global OSM instance, but could be quite useful for a containerized version of OSM. 

cc @geohacker @vgeorge @batpad @sethvincent

**Comment by geohacker** [comment]
> Should the API also clone or somehow mirror a user's added POI's and ways? 

This would probably be a lot of additional work to do properly. In fact, once authenticated, with the current implementation plan, a user can see all the GPX and photos uploaded by users and not limited to the authenticated user. 

I like this idea, but I think we might end up writing queries to the OSM API that we should probably stay away at this moment. We would also have to build filters like 'show edits only from Observe' which would be pretty complex to do.

**Comment by geohacker** [comment]
Tracking in https://github.com/developmentseed/observe-api/issues
