### ISSUE TITLE
Ability to take photos

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe#90]
We should allow users to take pictures from the field. While mapping, users may not have all the time to enter all attribute information to move faster and cover as much ground as possible. 

Being able to take pictures will provide the ability to view these later on and add additional attributes to POIs from a desktop editor like JOSM or on Observe. 

The basic functionality should be:
1. Take a photo any time in the app
2. Take a photo associated to a feature (for example, while creating / editing a POI)
3. Submit these to the Observe API #89 
4. Ability to view photos associated to a POI and add attributes in Observe
5. Ability to list all photos in an area

cc @batpad @sethvincent @vgeorge

**Comment by habi** [comment]
Maybe you could integrate the Mapillary SDK (https://www.mapillary.com/developer), something like OsmAnd has done: https://osmand.net/features/mapillary

**Comment by LanesGood** [comment]
@geohacker for "4. Ability to view photos associated to a POI and add attributes in Observe", is the user adding attributes to the photo, or to the POI? What user-defined attributes for photos are available other than "description"?

**Comment by LanesGood** [comment]
Photo workflow mockups have been updated here:
https://invis.io/CGUB4COZKTB#/389451125_add-Photo--camera

**Comment by geohacker** [comment]
> is the user adding attributes to the photo, or to the POI? 

@LanesGood sorry I wasn't clear. The attributes are for the POI. There are no attributes to the photo apart from description at the moment.

**Comment by geohacker** [comment]
@LanesGood thank you, the mockups and the workflow looks really good to me. I just left a few comments.

**Comment by geohacker** [comment]
This is done.
