### ISSUE TITLE
Setup expo-location module

### ISSUE THREAD

**Issue by batpad** [developmentseed/observe#97]
The Expo Location module seems to have good reviews around performance, etc.

To install it, we need to follow the instructions here: https://github.com/expo/expo/tree/master/packages/expo-location#installation-in-bare-react-native-projects

This requires us to install and setup `react-native-unimodules`: https://github.com/unimodules/react-native-unimodules

This seems a little bit involved, tweaking a few of the Java files, etc. @geohacker I'll work on the Android setup, may ask for your help on the Cocoapods / iOs side.

Relates to #87

**Comment by batpad** [comment]
I was able to get `unimodules` installed and `expo-location` working on Android. In this commit, I was able to get `watchPositionAsync` working - https://github.com/developmentseed/observe/commit/c98a1cb16c495a693453233ee633b0cf91423488 - you should see location updates in the console. However, this method only works when the app is in the foreground.

To get background location updates to work, we need to use `startLocationUpdatesAsync`: https://github.com/developmentseed/observe/commit/c98a1cb16c495a693453233ee633b0cf91423488 . This requires us to install `expo-task-manager` and setup a Task to run in the background.

I have done `yarn add expo-task-manager` and added the relevant bits of code to the `GPSTracker` component:

To define the task:
```
TaskManager.defineTask(LOCATION_TASK_NAME, ({ data: { locations }, error }) => {
  if (error) {
    console.log('location watch error', error)
  }
  console.log('Received new locations', locations)
})
```

To start listening to updates:

```
    await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
      accuracy: Location.Accuracy.BestForNavigation,
      timeInterval: 1000,
      distanceInterval: 5,
      foregroundService: {
        notificationTitle: 'Observe',
        notificationBody: 'Observe is capturing GPS traces',
        notificationColor: '#ff0000'
      },
      pauseUpdatesAutomatically: true
    })
```

Am getting the following error when running on device:

```
Attempt to invoke interface method 'void org.unimodules.interfaces.taskManager.TaskServiceInterface.setTaskManager(org.unimodules.interfaces.taskManager.TaskManagerInterface, java.lang.String)' on a null object reference
```

Was unable to find anything about this error online, will continue digging. However, the documentation on `Expo` seems a bit confusing: https://docs.expo.io/versions/latest/sdk/task-manager/#installation - it says: `For managed apps, you'll need to run expo install expo-task-manager. It is not yet available for bare React Native apps. If you're using the bare workflow, React Native's Headless JS might suit your needs.` - I'm not sure if that means it will just not work for us since we are not using Expo as a "managed app". I have a couple of hunches I'll follow down, but I maybe a bit stuck in figuring out a resolution to this.

**Comment by batpad** [comment]
This issue doesn't make the situation look very good / looks like TaskManager does not work yet in a "bare" app, and there don't seem to be alternatives suggested on getting background location on the ticket: https://github.com/expo/expo/issues/3453

**Comment by batpad** [comment]
I have implemented the `expo` and `expo-location` integration on Android here: https://github.com/developmentseed/observe/pull/99

This seems to work in the app to get foreground location. Based on discussion, we have decided to wait for upstream to hopefully figure out issues to be able to run background location tracking.

The problem is that with the addition of `unimodules`, tests are failing since `unimodules` adds a few things to NativeModules and we'd need to mock them for our tests.

There exists a package, that one can use as a Jest `preset`, that includes mocks for all the things `expo` and `unimodules` would need: https://github.com/expo/expo/tree/master/packages/jest-expo

The options here seem to be either just follow down each failing mock as we run tests and add those in similar to how we've been mocking the other NativeModules. Or, try and use this library with all the mocks baked in. We would need to set that as the Jest preset to use it out-of-the-box though and that worries me a little since we are not a full Expo managed app.

Anyway, just documenting the thought process - I'll try both of these paths and try and get a feel for which seems better to do. cc @geohacker @sethvincent

**Comment by batpad** [comment]
@sethvincent the only test that fails is the App.js test: https://github.com/developmentseed/observe/blob/develop/__tests__/App.js

That test doesn't do so much until we do more snapshot rendering - how bad would it be to remove this test for now if the mocking is turning out to be a rabbit-hole? I'll work on it anyway, just thought it's useful to mention that that is the only affected test, and check how important you feel this test is.

**Comment by batpad** [comment]
Did not have any luck with switching the preset to `jest-expo` - that caused more errors and I do not think that is a good idea.

Am having a bit of a hard time finding the mocks we'd need from https://github.com/expo/expo/blob/master/packages/jest-expo/src/preset/expoModules.js or even being sure if that's the right place to look. Am going to pause on this and consult with @sethvincent .

**Comment by geohacker** [comment]
Done and done!
